spring:
  config:
    activate.on-profile: dev
    import:
      - ${SECURITY_PATH:classpath:security}/datasource-dev.yml
      - ${SECURITY_PATH:classpath:security}/jwt.yml
      - ${SECURITY_PATH:classpath:security}/cors.yml
      - ${SECURITY_PATH:classpath:security}/logback.yml
      - ${SECURITY_PATH:classpath:security}/actuator.yml
      - ${SECURITY_PATH:classpath:security}/cache-dev.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
