# Default In-Memory H2
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:momo;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE  # MySQL 호환 모드
      username: sa

--- # MySQL Remote Test Server
spring:
  config:
    activate.on-profile: local-remoteDB
    import: classpath:security/datasource-dev.yml
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    defer-datasource-initialization: false
