name: Frontend Discord Notification

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  PR-Notification:
    runs-on: ubuntu-latest
    if: github.event.pull_request.title.startsWith('[FE]') || github.event.issue.title.startsWith('['FE_DISCORD_WEBHOOK_URL']')
    steps:
      - name: Send Discord Notification for Frontend
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\":\"A new PR/Issue for Frontend: ${{ github.event.pull_request.title || github.event.issue.title }}\"}" \
          ${{ secrets.FE_DISCORD_WEBHOOK_URL }}
